### ISSUE TITLE
AirPlay to chromecast

### ISSUE THREAD

**Issue by jflefebvre06** [hassio-addons/addon-aircast#114]
Hello
Could you please tell me if an addon exist for AirPlay to chromecast (the reverse of addon-aircast)
Thanks

**Comment by frenck** [comment]
Thanks for the bug report, but it obviously isn't a bug report...

Don't know. Use Google.

**Comment by iroQuai** [comment]
I'm looking for the same thing! Google doesn't really give anything. I'll keep searching!
