### ISSUE TITLE
Chrome cast not discovered without restart

### ISSUE THREAD

**Issue by idiotzoo** [hassio-addons/addon-aircast#123]
# Problem/Motivation
Essentially re-opening issue 50. It used to be that aircast would discover the chromecast audio devices more or less immediately, now it seems not to find them until aircast is restarted. This makes it far less effective than it once was. I’m not sure when behaviour changed. 

> (Why the issue was filed)

## Expected behavior
When chromecast audio Is powered on and joins the network, Aircast should quickly discover this
And make it available to airplay

> (What you expected to happen)

## Actual behavior
Chromecast is not discovered until aircast is restarted

> (What actually happened)

## Steps to reproduce
Power cycle chromecast audio

**Comment by idiotzoo** [comment]
Just a bump to prevent this issue automatically closing

**Comment by Mottemania** [comment]
Yeah. Still the same for me.

**Comment by idiotzoo** [comment]
Just another bump to keep this issue alive

**Comment by andreimoraru** [comment]
Issues is still reproduced on 3.3.0 version of Aircast Home Assistant add-on
