### ISSUE TITLE
icon needs some color

### ISSUE THREAD

**Issue by b3nj1** [hassio-addons/addon-aircast#129]
# Problem/Motivation

This is "nice to have".

In the Add-Ons settings page, the indicator whether an Add-Ons is running or not is that it has color or is greyscale. AirCast's active icon is black and white, so its state can't be inferred without taking additional steps (hoover or entering Add-On page). 
<img width="692" alt="image" src="https://user-images.githubusercontent.com/13173423/148992272-4c604b22-9830-4174-9a59-fe8b6ee04369.png">

## Proposed changes

Add some color to the icon :)

**Comment by frenck** [comment]
Not something I care to spend time on. Sorry.
Feel free to contribute others in a PR.
