### ISSUE TITLE
Airplay 2 Multiroom Support

### ISSUE THREAD

**Issue by pandaboy6621** [hassio-addons/addon-aircast#142]
Is it possible to change it from airplay to multiroom Airplay 2 via [this GitHub project](https://github.com/mikebrady/shairport-sync/blob/development/AIRPLAY2.md)? Also can you add a way to individually adjust the audio sync with a milisecond offset slider?

**Comment by frenck** [comment]
I cannot do either of those. Addons wrap existing applications. This add-on runs on AirConnect; if they add support for things like that, we can consider adding it as well.
