### ISSUE TITLE
Installation on Home Assistant container

### ISSUE THREAD

**Issue by Crafter89** [hassio-addons/addon-aircast#149]
How can I install this plugin for Home assistant docker container? I don't have an add-on store.

**Comment by frenck** [comment]
You can't. 🤷

**Comment by Crafter89** [comment]
There is no way of manually installing it?

**Comment by frenck** [comment]
This is an Home Assistant add-on, if you don't have an installation that supports add-on, this repository is completely useless to you. You can't use it.
