### ISSUE TITLE
Issue using AirCast - AddOn runs without errors, but no Speakers get discovered.

### ISSUE THREAD

**Issue by v1-valux** [hassio-addons/addon-aircast#154]
Hey @frenck ,

I want to use the hass.io AirCast Add-On for my ChromeCast devices in Homeassistant.

I am able to use other Services related to Airplay / Chromecast on every Device on my network, though my addon, like some other peoples too, seems not to find any Speakers and logging stops right after "Start:663 Binding to x.x.x.x" 

I also have tried installing HomeAssistant on a different Network (same way as the first instance, over the rpi4 arm64 installation script (dockerized))..
Same problem there aswell.

Both networks use a FRITZ!Box as router and wired eth0 DHCP configuration within homeassistant.
I am not able to see any issues within DNS or supervisor container..

I'm using no network devices between the RPi and the router, which could potentially block multicast I guess, but I am not able to find the issue..

As all docs state that the installation is straightforward and no other issue like that got resolved so far (https://github.com/hassio-addons/addon-aircast/issues/30 for example), I don't know how to find out whats wrong..

It would be great if someone could just lead me in the right direction, debugging this problem..
Any ideas how to find the issue?

Many thanks in advance!

-V

**Comment by v1-valux** [comment]
I forgot to mention, I'm also using Pi-Hole as a DNS Server in my network.. 
Does that impact the Addon somehow? (All other devices also use Pi-Hole as DNS via DHCP, but seem to work with AirPlay just fine..)

**Comment by v1-valux** [comment]
I did not have any success without pihole neither..
Does anyone have an idea how to debug this?

**Comment by v1-valux** [comment]
well.. thanks for the update @frenck.
After I updated to Version 3.5.1 today, it suddenly works like a charm.

Happy Holidays!
o/

**Comment by frenck** [comment]
> After I updated to Version 3.5.1 today, it suddenly works like a charm.

Oh cool! That is a nice surprise. Thanks for letting me know 👍 

Happy Holidays to you too! 🎄 

../Frenck
