### ISSUE TITLE
Audio delay compared to video

### ISSUE THREAD

**Issue by damiano75** [hassio-addons/addon-aircast#16]
# Problem/Motivation

> I have a delay of about 1 second between audio and video using Netflix on my iPad and a google home mini like an airplay audio speaker

# Expected behavior
> I want to watch video on my iPad and use google home mini like an audio speaker

## Actual behavior

> but audio and video are not synchronized

## Proposed changes

> Is there a way to adjust audio and video synchronization?

**Comment by frenck** [comment]
This will not be fixable, due to the nature of briding and transcoding audio formats.
