### ISSUE TITLE
Chromecast devices have plus symbols next to them

### ISSUE THREAD

**Issue by tonyshixd** [hassio-addons/addon-aircast#160]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior
![IMG_51CACDAC6FC9-1](https://user-images.githubusercontent.com/19269547/210005750-9ac465f0-53ca-49d7-b9f7-273527b9946c.jpeg)
> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by tjorim** [comment]
Not an issue, intended behavior.

**Comment by tonyshixd** [comment]
Is there a way to remove the plus symbol?

**Comment by tjorim** [comment]
Yes, please read the documentation: https://github.com/hassio-addons/addon-aircast/blob/main/aircast/DOCS.md#tweaking-aircast
You can change the config file and rename the players to whatever you like.

**Comment by tonyshixd** [comment]
Perfect! Thank you so much!
