### ISSUE TITLE
Can't rename (or forget) a Google Home Device

### ISSUE THREAD

**Issue by snickell** [hassio-addons/addon-aircast#185]
Short version: it would be great to have a UI to "reset everything" by deleting `aircast.xml`, or automatic updating of aircast.xml names when the google home device is renamed. Because aircast entries are tied to google home device's hardware address and not updated after first discovery, you can't rename an aircast device initial creation.

Background: I moved a google home speaker from my bathroom to the living room about a year ago. I renamed the speaker to "Living Room Speaker". Unfortunately the name continued to appear to Apple devices as "Google Home Bathroom+".

- In the Google Home official app, the device has the new name: Living Room Speaker.
- In all Hassio device entries, automations, etc it has the new name: Living Room Speaker.
- I tried uninstalling the aircast addon and rebooting home assistant, no change.
- The aircast log showed the correct name when starting up: `AddCastDevice:646 [0x32bc6b10]: adding renderer (Living Room Speaker) with mac CCCCF04509EA

I finally found the problem using the Terminal:
- `config/aircast.xml` contained the old name (Google Home Bathroom+) and was not being updated, and was not deleted upon uninstall either.
- As soon as I updated the name in aircast.xml and restarted the add-on, Apple devices saw the new name! Success!

**Comment by tjorim** [comment]
The 'UI' to change the name (or other settings) of a speaker or reset everything altogether is some add-on like file editor, samba share, ftp, studio code server...
