### ISSUE TITLE
Issue broadcast on Google Chromecast

### ISSUE THREAD

**Issue by ffblanch** [hassio-addons/addon-aircast#186]
Hi,
Fist, I want to say this add on is a must in HA. I really like it. I'm using then with many Google devices and an IPhone. Since couple of weeks, only on chromecast, the broadcast spends only 5 seconds. All others devices are working well. I factory reset my device and the error is still there. When I broadcast with Spotify everything is fine. 
Thanks

**Comment by pretenda** [comment]
I’m having the same issue. It’s hosted on my home assistant server, trying to send Apple Music on my iPhone 12, to my nest home hub max.

**Comment by litecross91** [comment]
https://github.com/philippe44/AirConnect/issues/479
In principle, the problem has been solved. When will the change be included in the addon?

**Comment by frenck** [comment]
@litecross91 Next iteration. Today my focus was on shipping base image updates.

**Comment by litecross91** [comment]
@frenck Thank you! We're looking forward to getting the aircast working properly for the Next Hub devices. Philippe44 did a good job based on the feedback from the other forum. 
Maybe do you know when have you time for the next iterarion?

**Comment by litecross91** [comment]
I updated to 4.0.1 today but with the Nest Hub 1st gen not working. Same issue, play 5 sec after stop.
Or have you not yet implemented the fix from the other forum?

**Comment by NateGr** [comment]
> I updated to 4.0.1 today but with the Nest Hub 1st gen not working. Same issue, play 5 sec after stop. Or have you not yet implemented the fix from the other forum?

Same. I seem to be experiencing the same issue.  Seems that when the artwork and the track title is sent is when the 5 second timer begins and it shutsdown the stream.  Nothing in the logs that can be seen.  Happy to help diagnose, let me know what I can provide to make it easier.

**Comment by litecross91** [comment]
> > I updated to 4.0.1 today but with the Nest Hub 1st gen not working. Same issue, play 5 sec after stop. Or have you not yet implemented the fix from the other forum?
> 
> Same. I seem to be experiencing the same issue. Seems that when the artwork and the track title is sent is when the 5 second timer begins and it shutsdown the stream. Nothing in the logs that can be seen. Happy to help diagnose, let me know what I can provide to make it easier.

On the original AirConnect forum, the developer has already solved the bug, it just needs to be implemented in this Addon.
https://github.com/philippe44/AirConnect/issues/479

**Comment by NateGr** [comment]
> > > I updated to 4.0.1 today but with the Nest Hub 1st gen not working. Same issue, play 5 sec after stop. Or have you not yet implemented the fix from the other forum?
> > 
> > 
> > Same. I seem to be experiencing the same issue. Seems that when the artwork and the track title is sent is when the 5 second timer begins and it shutsdown the stream. Nothing in the logs that can be seen. Happy to help diagnose, let me know what I can provide to make it easier.
> 
> On the original AirConnect forum, the developer has already solved the bug, it just needs to be implemented in this Addon. [philippe44/AirConnect#479](https://github.com/philippe44/AirConnect/issues/479)

Ah. The fix has merged in yet. Got it. Will sit tight.

**Comment by Adam-Kay** [comment]
Came here to report the same thing, hopefully it gets merged in soon

**Comment by ffblanch** [comment]
I took a test this morning, and I have always had the same problem.

**Comment by litecross91** [comment]
I was not waiting for this. I set up the original AirConnect on a separate linux server. https://github.com/philippe44/AirConnect
It works perfectly. 
You don't need Home Assistant for everything...

**Comment by jfredyp** [comment]
Came to report the same error on Google Nest Hub but if I share with Google Nest 1 It's Works

**Comment by kintaroju** [comment]
Hi,

I am inquiring if AirConnect code got updated yet by chance, still having the same issues.

Cheers,
Jon

**Comment by MichaelZ333111** [comment]
Same issue issue unfortunately.

**Comment by frenck** [comment]
Just shipped v4.1.0

https://github.com/hassio-addons/addon-aircast/releases/tag/v4.1.0

**Comment by ffblanch** [comment]
Thanks for your help @frenck it’s work great 💪🏼

**Comment by kintaroju** [comment]
thanks @frenck , the update works like a champ!
