### ISSUE TITLE
Feature Request: Airplay 2 Support

### ISSUE THREAD

**Issue by victor-vz** [hassio-addons/addon-aircast#189]
Love the Addon abd how smoothly it runs (even better than my HomePods). I would love to be able to connect multiple speakers. If it is not 100% synchronized it would not be a big problem (speakers on different floors)

**Comment by tjorim** [comment]
Create a speaker group in the Google Home app, aircast should pick them up (at least from my experience).

**Comment by frenck** [comment]
Sorry, that is not something the add-on can provide.

Closing, as this is not an issue but an feature request.

../Frenck
