### ISSUE TITLE
aircast not seeing any devices

### ISSUE THREAD

**Issue by ideal2545** [hassio-addons/addon-aircast#19]
# Problem/Motivation

Aircast does not show that its finding any cast devices

## Expected behavior

The log file should show some information related to what its finding and airplay apps should show google cast devices

## Actual behavior
Aircast starts up and binds to address but nothing happens after. 

## Steps to reproduce

Just click start.

**Comment by ideal2545** [comment]
Here's a log spit out while set to 'trace':

`    empty
            else
                .log_level
            end
        else
            .log_level
        end
[12:47:53] TRACE: bashio::config: log_level
[12:47:53] TRACE: bashio::jq: /data/options.json if (.log_level == null) then
            null
        elif (.log_level | type == "string") then
            .log_level // empty
        elif (.log_level | type == "boolean") then
            .log_level // false
        elif (.log_level | type == "array") then
            if (.log_level == []) then
                empty
            else
                .log_level[]
            end
        elif (.log_level | type == "object") then
            if (.log_level == {}) then
                empty
            else
                .log_level
            end
        else
            .log_level
        end
[12:47:53] TRACE: bashio::string.lower: trace
[12:47:53] TRACE: bashio::config: latency_rtp
[12:47:53] TRACE: bashio::jq: /data/options.json if (.latency_rtp == null) then
            null
        elif (.latency_rtp | type == "string") then
            .latency_rtp // empty
        elif (.latency_rtp | type == "boolean") then
            .latency_rtp // false
        elif (.latency_rtp | type == "array") then
            if (.latency_rtp == []) then
                empty
            else
                .latency_rtp[]
            end
        elif (.latency_rtp | type == "object") then
            if (.latency_rtp == {}) then
                empty
            else
                .latency_rtp
            end
        else
            .latency_rtp
        end
[12:47:53] TRACE: bashio::config: latency_http
[12:47:53] TRACE: bashio::jq: /data/options.json if (.latency_http == null) then
            null
        elif (.latency_http | type == "string") then
            .latency_http // empty
        elif (.latency_http | type == "boolean") then
            .latency_http // false
        elif (.latency_http | type == "array") then
            if (.latency_http == []) then
                empty
            else
                .latency_http[]
            end
        elif (.latency_http | type == "object") then
            if (.latency_http == {}) then
                empty
            else
                .latency_http
            end
        else
            .latency_http
        end
[12:47:53] TRACE: bashio::config.true: drift
[12:47:53] TRACE: bashio::config: drift
[12:47:53] TRACE: bashio::jq: /data/options.json if (.drift == null) then
            null
        elif (.drift | type == "string") then
            .drift // empty
        elif (.drift | type == "boolean") then
            .drift // false
        elif (.drift | type == "array") then
            if (.drift == []) then
                empty
            else
                .drift[]
            end
        elif (.drift | type == "object") then
            if (.drift == {}) then
                empty
            else
                .drift
            end
        else
            .drift
        end
[12:47:53] TRACE: bashio::var.true: true
[12:47:53.420203] main:914 Starting aircast version: v0.2.9.0 (Apr 20 2019 @ 14:33:41)
[12:47:53.420460] Start:689 Binding to 192.168.1.15
`

**Comment by ideal2545** [comment]
the devices are not on a separate subnet, HA see's them just fine

**Comment by ideal2545** [comment]
I have resolved this issue, my switch had IGMP snooping on, disabling that made everything work much better.

**Comment by frenck** [comment]
Ooh, that might cause it indeed! Never thought about that before, I think we should add a note to the add-on manaul on that.

**Comment by ideal2545** [comment]
Yeah you know it actually solved a lot of real random problems I was having with my wemo switches, random issues with google cast devices and the homekit integration, everything has suddenly become more stable.
