### ISSUE TITLE
Unexpected high system load.

### ISSUE THREAD

**Issue by magnusoverli** [hassio-addons/addon-aircast#2]
# Problem/Motivation

Unexpected high load to system.

## Expected behavior

While running the add-on, I´d expect to see a slight increase in load while not playing any audio, possibly more when actually playing audio using the add-on.

## Actual behavior

As soon as the add-on is started, the CPU load skyrockets from approximately 2%-4% to a steady 25%-27%. This is without playing any audio.

## Steps to reproduce

Install and start the add-on while monitoring the system load.

## Hardware/System running hassio

Raspberry Pi 3

As seen in the attached image, for most of the last 24 hours I've been running both the AirCast and the AirSonos add-ons. At about 19:30 tonight I stopped the AirSonos add-on, and then at around 23:00 I stopped the AirCast add-on. Behavior is the same for both add-ons.

<img width="358" alt="skjermbilde 2018-01-03 kl 23 17 17" src="https://user-images.githubusercontent.com/3475247/34542478-03e51c8e-f0dd-11e7-800f-017531610483.png">

**Comment by mnoorenberghe** [comment]
If this is a 4-core machine then I had the same problem since I had the process at 100% of one core. I had to disable the add-on as a result. I was using a generic Linux install on Ubuntu desktop.

**Comment by frenck** [comment]
Bug has been identified. Planning for a fix.

**Comment by frenck** [comment]
This issue has been fixed in v0.2.0.
