### ISSUE TITLE
Cant connect on ios 18 or sequoia

### ISSUE THREAD

**Issue by therosaer** [hassio-addons/addon-aircast#207]
After installing the latest developer betas of both ios 18 and macos sequoia it seems that the airplay 1 functionality is broken, when it tries to connect to a aircast device it repeats the same errors and cant work. On a ios 17 device or macos ventura it works fine so it is a compatibility issue with the latest versions. The logs display
```
[11:25:04.897] rtsp_thread:333 got RTSP connection 15
[11:25:05.121] http_read_line:1101 disconnected on the other end 15
[11:25:05.121] rtsp_thread:348 RTSP close 15
[11:25:05.313] rtsp_thread:333 got RTSP connection 15
[11:25:05.333] http_read_line:1101 disconnected on the other end 15
[11:25:05.333] rtsp_thread:348 RTSP close 15
```
Hope it is just a issue in betas as usually on the developer and public beta some functionalitys are broken but after the official release it works again, still i wanted to open the issue so if somebody wants to upgrade to either versions they know that it will break aircast.

**Comment by rpatin411** [comment]
I am also experiencing this issue on iOS 18 Public Beta. Fingers crossed it gets resolved as new betas are released! 🤞

**Comment by rpatin411** [comment]
This issue appears to be fixed in iOS 18 Public Beta 3.

**Comment by sinclairpaul** [comment]
According to the upstream issue, it is resolved <https://github.com/philippe44/AirConnect/issues/532>

Either way, it would be an issue upstream rather than the addon itself.
