### ISSUE TITLE
Feature Request: AirPlay 2

### ISSUE THREAD

**Issue by adamoberley** [hassio-addons/addon-aircast#21]
News is that AirPlay2 with multi-room is working now. Since it has been reverse engineered, is it possible that AirCast will see it added?

_Originally posted by @invano in https://github.com/mikebrady/shairport-sync/issues/535#issuecomment-560413392_

**Comment by frenck** [comment]
Duplicate of #14

**Comment by frenck** [comment]
Add-ons wrap existing applications is it not up to us to implement it.

**Comment by Neustradamus** [comment]
@frenck: The previous ticket is blocked and closed.

Can you unlock and reopen?
