### ISSUE TITLE
Airplay protocol 2 support

### ISSUE THREAD

**Issue by Morriz** [hassio-addons/addon-aircast#218]
# Problem/Motivation

Protocol v1 has been superseded over 5 years now by v2, and v1 has very limited feature support.

Many issues with v1 exist now:
- v1 devices are not seen by v2 devices as targets
- v1 devices can't be grouped
- ...

How much work would it be to support v2?

**Comment by Morriz** [comment]
@JohannVR created this: https://github.com/JohannVR/JohannVRs-Home-Assistant-Addons/tree/main/Airplay2

Maybe it has all the ingredients?

**Comment by JohannVR** [comment]
This addon should support Airplay version 2, or what is your question?

**Comment by Morriz** [comment]
Are you sure that this aircast add-on advertises devices on protocol v2? Then I should be able to stream music to it from my iDevices, by selecting multiple output devices. But the aircast devices are not shown in the multi output grouping, only as v1 (which turns of any v2 selected devices upon selecting).

**Comment by Morriz** [comment]
Plus, my HomePod isn't currently seeing the aircast devices at all so it can't add them to it's output.

**Comment by frenck** [comment]
This add-on is built on top of https://github.com/philippe44/AirConnect/

I suggest to raise a feature request on their end instead.

Thanks 👍 

../Frenck
