### ISSUE TITLE
Excluding devices feature

### ISSUE THREAD

**Issue by pawelbudynek** [hassio-addons/addon-aircast#22]
Hi Guys, 

I am very pleased with this addon. Thank for that!

I've been wondering if it is possible to give us an option to exclude some speakers from this addon. I do have more than couple google mini and every single one is discovered as airplay device.

I mean... this is great, but I am not using it anyway, as I have cool ass 40 years old speakers with google chromecast audio and all music is streaming into this speakers.

Also additional options on airplay devices list makes my Girl all confused. Please do not let ma girl to get lost in the Home Automatization World ;)

**Comment by frenck** [comment]
Yes, see: <https://github.com/hassio-addons/addon-aircast#tweaking-aircast>

The add-on is running AirConnect (in case you are looking for more information about that configuration).
