### ISSUE TITLE
Question, is it possible to install without the add-on store?

### ISSUE THREAD

**Issue by gregbenner** [hassio-addons/addon-aircast#23]
# Problem/Motivation
Sorry to ask here but I've scoured the internet and all I can find is that hass.io and home assistant are a bit different? Is there no way to make use of this if I don't have an add-on panel?
Thanks!
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
You need Hass.io to install any addons.

Why not switch to Hass.io? :)
