### ISSUE TITLE
Feature request; cover-art

### ISSUE THREAD

**Issue by GitHubLuigi** [hassio-addons/addon-aircast#28]
Hi Franck,

First of all, thx for creating this amazing add-on!
I was wondering if it is possible to display cover-art in hassio’s (default) media player.
When I stream music from Apple Music to a Google Home Mini (using AirCast), it won’t show any covers for example.

**Comment by frenck** [comment]
Add-ons wrap existing applications, in this case, airconnect.
Please submit those types of feature requests to the source project.

Thanks 👍
