### ISSUE TITLE
Cannot connect after updating to Aircast v2.4.0

### ISSUE THREAD

**Issue by coolguymatt** [hassio-addons/addon-aircast#31]
# Problem/Motivation

iPhone cannot connect to Aircast devices

## Expected behavior

Connect and play successfully

## Actual behavior

![image](https://user-images.githubusercontent.com/35379891/97171401-c6d54980-1763-11eb-81f9-3397d28c04cd.png)

In the logs I get this:

```
[08:14:42.598461] rtsp_thread:351 got RTSP connection 32
[08:14:47.461219] handle_rtsp:399 [0xb52179c0]: challenge dOLOqhKzw1hKkLjjGhxrew==
[08:14:47.489435] handle_rtsp:392 [0xb52179c0]: received ANNOUNCE
[08:14:47.504442] handle_rtsp:591 [0xb52179c0]: responding:
RTSP/1.0 200 OK
Audio-Jack-Status: connected; type=analog
CSeq: 4

[08:14:47.520407] handle_rtsp:392 [0xb52179c0]: received SETUP
[08:14:47.525402] handle_rtsp:591 [0xb52179c0]: responding:
RTSP/1.0 200 OK
Transport: RTP/AVP/UDP;unicast;mode=record;control_port=35976;timing_port=42420;server_port=42014
Session: DEADBEEF
Audio-Jack-Status: connected; type=analog
CSeq: 5

[08:14:47.533143] handle_rtsp:392 [0xb52179c0]: received RECORD
[08:14:48] INFO: Starting the AirCast server...
[08:14:48.652824] main:952 Starting aircast version: v0.2.28.2 (Oct 24 2020 @ 13:22:52)
[08:14:48.653393] Start:716 Binding to 192.168.1.184
```
And then the normal startup procedure.

## Steps to reproduce

Cast to any Aircast device

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by jacoknapp** [comment]
I am also getting this exact same issue, it started happening after the upgrade

**Comment by sukhsung** [comment]
I'm getting the same issue as well. I installed aircast on my virtual machine yesterday.

**Comment by jacoknapp** [comment]
Actually looking at this, the code appears to have been bumped a version on the binary side. I'll check it out. On a different note, do we just want to pull the binaries down from git raw on build/start? That way we could keep them up to date with the air connect repo, or are we more worried about the versioning control and potential config changes?

**Comment by GherardS** [comment]
Resolve in the next update? When?

**Comment by jacoknapp** [comment]
It is for the master code the repository is based off of. Unfortunately the binary had been fixed from there, but the pull request has to be approved, or the issue has to be accepted and manually updated. Unfortunately until then this app is in a broken state until then.

**Comment by frenck** [comment]
it is on my shortlist. Please have a bit of patience.

**Comment by sukhsung** [comment]
@GherardS @jacoknapp apologies for @'s

I ended up making a temporary fork and revert to 8b35017 (last one before airconnect version upgrade). It seems to work fine.
You guys should be able to add https://github.com/sukhsung/addon-aircast to add-on repo and use it temporarily. 
You probably should uninstall the official version before doing so.

I'm planning to remove the forked version once official patch is rolled out.

**Comment by frenck** [comment]
⬆️ AirCast v2.4.1

<https://github.com/hassio-addons/addon-aircast/releases/tag/v2.4.1>
