### ISSUE TITLE
air connect only support audio, it does not support video to play movies or mirror screen.

### ISSUE THREAD

**Issue by hasan-fardan** [hassio-addons/addon-aircast#34]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Correct.

**Comment by hasan-fardan** [comment]
will it support video in the near future?

**Comment by frenck** [comment]
nope.

**Comment by hasan-fardan** [comment]
Is there any solution to make the Chromecast compatible with air connect?

**Comment by frenck** [comment]
?! No
