### ISSUE TITLE
Excluding specific devices

### ISSUE THREAD

**Issue by wrpooley** [hassio-addons/addon-aircast#35]
I see references to being able to edit the config file in order to limit the number of device you wish to make available but I have not been successful in doing that.  Is it possible to comment out the specific devices?  Whenever I do that, upon starting the add-on it just re-writes the xml file to the previous state.  Any help would be greatly appreciated!

**Comment by frenck** [comment]
Don't comment them out, disable them instead.

See upstream documentation: <https://github.com/philippe44/AirConnect#config-file-parameters>
