### ISSUE TITLE
Filter dynamic groups

### ISSUE THREAD

**Issue by statop** [hassio-addons/addon-aircast#36]
# Problem/Motivation

Infinite number of groups are added for dynamic speaker groups created via nest display. A new one each time you create a group.

## Expected behavior

The ability to disable auto add of speaker groups.

## Actual behavior

No way to disable auto add of speaker groups.

## Steps to reproduce

using a nest display or Google home app add/remove speakers to currently playing music.

## Proposed changes

A config that either disables auto add of speaker groups or even better just disables auto add of dynamic groups.

**Comment by frenck** [comment]
The add-on cannot do that, as the underlying software doesn't support that.

Add-ons wrap existing software, in this case, AirConnect.
