### ISSUE TITLE
Error when starting AirCast

### ISSUE THREAD

**Issue by andreasjacobsen93** [hassio-addons/addon-aircast#7]
Using 0.64.3
I get the following logs when starting AirCast:

```
worker [700] terminated by signal 9 (Killed)
worker [701] terminated by signal 9 (Killed)
worker [707] did not accept message -1 (Operation not permitted), kill it
worker [704] did not accept message -1 (Operation not permitted), kill it
worker [709] did not accept message -1 (Operation not permitted), kill it
worker [703] terminated by signal 9 (Killed)
worker [704] terminated by signal 9 (Killed)
worker [710] did not accept message -1 (Operation not permitted), kill it
worker [708] did not accept message -1 (Operation not permitted), kill it
worker [711] did not accept message -1 (Operation not permitted), kill it
worker [707] terminated by signal 9 (Killed)
worker [708] terminated by signal 9 (Killed)
```

I am using the standard values in the configuration.
How can I fix this?

**Comment by frenck** [comment]
I'm sorry, this does not help me. 

Do you have some more information?

**Comment by avaidyam** [comment]
I'm seeing a similar issue. I can't seem to find any AirCast logs, but if you know where they're found, I'll dig them up for you.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
[cont-init.d] 00-banner.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
s6-maximumtime: warning: child process crashed
[cont-finish.d] 99-message.sh: exited 111.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
```

**Comment by frenck** [comment]
Maybe the Supervisor logs give some more insights?
Also some more information about; Add-on version, Supervisor version, OS & OS Version, Hardware e.d. might help.

**Comment by surshis** [comment]
I am getting same error-
logs from the addon--
Log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
[cont-init.d] 00-banner.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
s6-maximumtime: warning: child process crashed
[cont-finish.d] 99-message.sh: exited 111.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.

shows 2 entries on System log---
18-03-30 04:23:39 INFO (SyncWorker_0) [hassio.docker.interface] Clean hassioaddons/aircast-armhf docker application
18-03-30 04:23:43 INFO (SyncWorker_0) [hassio.docker.addon] Start docker addon hassioaddons/aircast-armhf with version 0.3.0

**Comment by frenck** [comment]
Thank you @surshis...

Same question.
I need more information...

> Maybe the Supervisor logs give some more insights?
> Also some more information about; Add-on version, Supervisor version, OS & OS Version, Hardware e.d. might help.

**Comment by surshis** [comment]
@frenck
Add on version 0.3.0
Supervisor version -- 0.99
HASS IO version -- 0.66.1
Hardware- Raspberry pi 3


system logs- only 2 entries
18-04-02 18:28:09 INFO (SyncWorker_0) [hassio.docker.interface] Clean hassioaddons/aircast-armhf docker application
18-04-02 18:28:15 INFO (SyncWorker_0) [hassio.docker.addon] Start docker addon hassioaddons/aircast-armhf with version 0.3.0

**Comment by schettada** [comment]
Same error here as well. 

worker [1371] did not accept message -1 (Operation not permitted), kill it
worker [1384] did not accept message -1 (Operation not permitted), kill it
worker [1381] did not accept message -1 (Operation not permitted), kill it
worker [1377] did not accept message -1 (Operation not permitted), kill it
worker [1376] did not accept message -1 (Operation not permitted), kill it
worker [1382] did not accept message -1 (Operation not permitted), kill it
worker [1378] did not accept message -1 (Operation not permitted), kill it
worker [1379] did not accept message -1 (Operation not permitted), kill it
worker [1375] did not accept message -1 (Operation not permitted), kill it
worker [1373] did not accept message -1 (Operation not permitted), kill it
worker [1372] did not accept message -1 (Operation not permitted), kill it
worker [1371] terminated by signal 9 (Killed)
worker [1373] terminated by signal 9 (Killed)
worker [1374] terminated by signal 9 (Killed)
worker [1376] terminated by signal 9 (Killed)
worker [1380] terminated by signal 9 (Killed)
worker [1381] terminated by signal 9 (Killed)
worker [1382] terminated by signal 9 (Killed)
worker [1383] did not accept message -1 (Operation not permitted), kill it
worker [1372] terminated by signal 9 (Killed)
worker [1375] terminated by signal 9 (Killed)
worker [1377] terminated by signal 9 (Killed)
worker [1378] terminated by signal 9 (Killed)
worker [1379] terminated by signal 9 (Killed)
worker [1383] terminated by signal 9 (Killed)
worker [1384] terminated by signal 9 (Killed)
worker [1388] did not accept message -1 (Operation not permitted), kill it
worker [1385] did not accept message -1 (Operation not permitted), kill it
worker [1390] did not accept message -1 (Operation not permitted), kill it
worker [1386] did not accept message -1 (Operation not permitted), kill it
worker [1389] did not accept message -1 (Operation not permitted), kill it
worker [1398] did not accept message -1 (Operation not permitted), kill it
worker [1394] did not accept message -1 (Operation not permitted), kill it
worker [1396] did not accept message -1 (Operation not permitted), kill it
worker [1387] did not accept message -1 (Operation not permitted), kill it
worker [1385] terminated by signal 9 (Killed)
worker [1386] terminated by signal 9 (Killed)
worker [1387] terminated by signal 9 (Killed)
worker [1388] terminated by signal 9 (Killed)
worker [1389] terminated by signal 9 (Killed)
worker [1390] terminated by signal 9 (Killed)
worker [1394] terminated by signal 9 (Killed)
worker [1396] terminated by signal 9 (Killed)
worker [1398] terminated by signal 9 (Killed)
worker [1392] did not accept message -1 (Operation not permitted), kill it
worker [1397] did not accept message -1 (Operation not permitted), kill it
worker [1395] did not accept message -1 (Operation not permitted), kill it
worker [1391] did not accept message -1 (Operation not permitted), kill it
worker [1391] terminated by signal 9 (Killed)
worker [1392] terminated by signal 9 (Killed)
worker [1395] terminated by signal 9 (Killed)
worker [1397] terminated by signal 9 (Killed)
worker [1393] did not accept message -1 (Operation not permitted), kill it
worker [1399] did not accept message -1 (Operation not permitted), kill it
worker [1393] terminated by signal 9 (Killed)
worker [1399] terminated by signal 9 (Killed)
worker [1400] did not accept message -1 (Operation not permitted), kill it
worker [1401] did not accept message -1 (Operation not permitted), kill it
worker [1400] terminated by signal 9 (Killed)
worker [1401] terminated by signal 9 (Killed)
worker [1402] did not accept message -1 (Operation not permitted), kill it
worker [1402] terminated by signal 9 (Killed)
worker [1403] did not accept message -1 (Operation not permitted), kill it
worker [1403] terminated by signal 9 (Killed)
worker [1405] did not accept message -1 (Operation not permitted), kill it
worker [1405] terminated by signal 9 (Killed)
worker [1406] did not accept message -1 (Operation not permitted), kill it
worker [1408] did not accept message -1 (Operation not permitted), kill it
worker [1407] did not accept message -1 (Operation not permitted), kill it
worker [1404] did not accept message -1 (Operation not permitted), kill it
worker [1404] terminated by signal 9 (Killed)
worker [1406] terminated by signal 9 (Killed)
worker [1407] terminated by signal 9 (Killed)
worker [1409] did not accept message -1 (Operation not permitted), kill it
worker [1408] terminated by signal 9 (Killed)
worker [1409] terminated by signal 9 (Killed)
worker [1410] did not accept message -1 (Operation not permitted), kill it
worker [1410] terminated by signal 9 (Killed)
worker [1412] did not accept message -1 (Operation not permitted), kill it
worker [1412] terminated by signal 9 (Killed)

**Comment by surshis** [comment]
any updates?

**Comment by frenck** [comment]
The addon has been updated, this issue has not been fixed specifically, nevertheless, everything has been updated and mostly re-written. 

Does this issue still occur?

**Comment by surshis** [comment]
@frenck  Thanks...updated...now getting new error---
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0xf227ff, 0x16)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/panic.go:566 +0x78 fp=0xbe8d99bc sp=0xbe8d99b0
runtime.sysMap(0x8d5b6000, 0x96da000, 0x96c90001, 0x15e07e8)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/mem_linux.go:227 +0x15c fp=0xbe8d99e4 sp=0xbe8d99bc
runtime.(*mheap).mapBits(0x15d1b20, 0x96d90000)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/mbitmap.go:159 +0xdc fp=0xbe8d99fc sp=0xbe8d99e4
runtime.(*mheap).sysAlloc(0x15d1b20, 0x100000, 0x1)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/malloc.go:430 +0x160 fp=0xbe8d9a50 sp=0xbe8d99fc
runtime.(*mheap).grow(0x15d1b20, 0x8, 0x0)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/mheap.go:726 +0x68 fp=0xbe8d9a84 sp=0xbe8d9a50
runtime.(*mheap).allocSpanLocked(0x15d1b20, 0x1, 0x0)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/mheap.go:630 +0x634 fp=0xbe8d9ab4 sp=0xbe8d9a84
runtime.(*mheap).alloc_m(0x15d1b20, 0x1, 0x10, 0x35d00, 0x0)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/mheap.go:515 +0x138 fp=0xbe8d9af0 sp=0xbe8d9ab4
runtime.(*mheap).alloc.func1()
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/mheap.go:579 +0x40 fp=0xbe8d9b0c sp=0xbe8d9af0
runtime.systemstack(0xbe8d9b20)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/asm_arm.s:261 +0xa8 fp=0xbe8d9b10 sp=0xbe8d9b0c
runtime.(*mheap).alloc(0x15d1b20, 0x1, 0x10, 0x100, 0x295b4)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/mheap.go:580 +0x58 fp=0xbe8d9b38 sp=0xbe8d9b10
runtime.(*mcentral).grow(0x15d2930, 0x0)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/mcentral.go:210 +0xb0 fp=0xbe8d9b64 sp=0xbe8d9b38
runtime.(*mcentral).cacheSpan(0x15d2930, 0x235a4)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/mcentral.go:91 +0x65c fp=0xbe8d9ba8 sp=0xbe8d9b64
runtime.(*mcache).refill(0x86a50000, 0x10, 0xbe8d9bd4)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/mcache.go:121 +0xd4 fp=0xbe8d9bbc sp=0xbe8d9ba8
runtime.(*mcache).nextFree.func1()
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/malloc.go:527 +0x28 fp=0xbe8d9bcc sp=0xbe8d9bbc
runtime.systemstack(0xbe8d9be8)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/asm_arm.s:261 +0xa8 fp=0xbe8d9bd0 sp=0xbe8d9bcc
runtime.(*mcache).nextFree(0x86a50000, 0x15ced10, 0x1046790, 0x15ce848, 0xbe8d9c00)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/malloc.go:528 +0x154 fp=0xbe8d9bf4 sp=0xbe8d9bd0
runtime.mallocgc(0xf0, 0xef4e60, 0x43401, 0x0)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/malloc.go:680 +0xca0 fp=0xbe8d9c94 sp=0xbe8d9bf4
runtime.newobject(0xef4e60, 0x1)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/malloc.go:807 +0x30 fp=0xbe8d9ca8 sp=0xbe8d9c94
runtime.malg(0x8000, 0x15ceda0)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/proc.go:2688 +0x20 fp=0xbe8d9cc4 sp=0xbe8d9ca8
runtime.mpreinit(0x15cf310)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/os_linux.go:251 +0x1c fp=0xbe8d9cd0 sp=0xbe8d9cc4
runtime.mcommoninit(0x15cf310)
	/yocto/resin-board/build/tmp/sysroots/x86_64-linux/usr/lib/arm-poky-linux-gnueabi/go/src/runtime/proc.go:507 +0x108 fp=0xbe8d9cf4 sp=0xbe8d9cd0
runtime.schedinit()

**Comment by frenck** [comment]
@surshis Maybe you did ran out of memory?
