### ISSUE TITLE
Streaming to Cast Group limited to 0-50% output volume range

### ISSUE THREAD

**Issue by davidaday** [hassio-addons/addon-aircast#8]
# Problem/Motivation

Streaming audio via Airplay from iOS devices to Google Cast groups causes Cast devices' volumes to be limited to the 0-50% range (as controllable by the Airplay source device)

## Expected behavior

Individual Chromecast devices (incl. Google Home and Chromecast Audio) appear to have the volume level from the Airplay source device mapped to the Chromecast's full 0-100% output range, as expected. Changing the volume on the source (iOS) device with either in-app or physical controls causes the Chromecast device to match the volume level accordingly. 

## Actual behavior

Using the same devices that individually acted as expected, but added into a Cast group, causes the Airplay source volume range to be mapped to 0-50% of the group's output. 

Using the volume controls on the Airplay source (iOS) device does adjust the output volume of the Chromecast group accordingly, where 50% on the Airplay device corresponds to a 25% volume level on the Chromecast group.

Also, while the Chromecast group's volume can be temporarily set higher with the Google Home app -independently of the Airplay device's set volume level - any change in the Airplay device's volume level, source selection incl track changes, muting, or device notifications that duck the audio level, resets the Chromecast group's volume to that of the Airplay device (between 0-50%)

## Steps to reproduce

1. Create a Google Cast group via the Google Home app
2. Airplay audio from an iOS device to the Cast group via AirCast v0.5.0 (Hass.io v0.72.1)
3. Set iOS output volume to 100%

## Proposed changes

Identify why the Airplay volume range is mapped differently for groups than individual devices, and correct it to match

**Comment by frenck** [comment]
I guess this was a default. For `v0.6.0` I've changed the default to 100%.
