### ISSUE TITLE
Yamaha Airplay

### ISSUE THREAD

**Issue by jbega** [hassio-addons/addon-aircast#83]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by jbega** [comment]
Hello. After installing the addon, my chromecast device is added and I can send it audio. I have a Yamaha AVR with Airplay (added with the musiccast integration in HA), any suggestions to send sound to the Yamaha avr?

**Comment by frenck** [comment]
> I have a Yamaha AVR with Airplay

Cool, however, this add-on doesn't do that, this is for chromecast -> airplay, not the other way around.

**Comment by jbega** [comment]
Thank you, I misunderstood the concept. I thought it was to send by airplay to any device with airplay and also adaptation so that the chromecast was recognized as airplay
