### ISSUE TITLE
all my devices show up as audio devices

### ISSUE THREAD

**Issue by bader515** [hassio-addons/addon-aircast#86]
**Hi,
This add-on works except that all my devices show up as audio devices.
I have a Google TV, and another TV with a built-in chrome cast and all of them are showing up as audio devices.
When I connect to them through airplay, I only get the audio through them.
I have a google home mini on the same network, and it's working perfectly when I use it through this add-on (I don't know if this would help identify the issue).
my add-on current version: 3.1.1
Home Assistant OS version: 6.0
Home Assistant core version: 2021.6.5
Home Assistant supervisor version: 2021.06.3**

**Comment by phixion** [comment]
aircast is an audiobridge between airplay and chromecast devices. In other words I don't think video is supported.

**Comment by frenck** [comment]
Video is not supported indeed, it is limited to Audio only.
