### ISSUE TITLE
AirCast continuously restarting

### ISSUE THREAD

**Issue by LennyPenny** [hassio-addons/addon-aircast#9]
# Problem/Motivation

Logs spam `PROTINFO: Starting the AirCast server`

## Expected behavior

It successfully starting 

## Actual behavior

Not starting and spamming `PROTINFO: Starting the AirCast server` in the logs

## Steps to reproduce

Start it

## System
Rock64 (it's armv8 so it's supported I think)

**Comment by ezar** [comment]
Same here!!

**Comment by frenck** [comment]
OS? Versions of things?
Anything in the Hass.io system output?

**Comment by ezar** [comment]
HassOS 1.5 x64

**Comment by ishmeetahuja** [comment]
Same issue here!!

**Comment by jpreiditsch** [comment]
Same issue on HassOS

**Comment by LennyPenny** [comment]
I'm on a debian stretch. 
The hassio logbook doesn't show anythign about aircast sadly

**Comment by LennyPenny** [comment]
Here's a full trace between the restarts: 
https://pastebin.com/Txgy0Jau

**Comment by jmhorowitz** [comment]
Same issue on HassOS on a RPI3

**Comment by frenck** [comment]
Fixed in `v0.6.0`.
